_BASE_: "../Base-RCNN-FPN-KINS.yaml"
#VIS_PERIOD: 500
MODEL:
  WEIGHTS: ""
  MASK_ON: True
  DEPTH:
    PREDICT: True
    NORMAL_MAP: True
    EXTRACT_NORMAL: True
    VISUALIZE_NORMAL: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "Parallel_Amodal_Visible_ROIHeads"
  ROI_MASK_HEAD:
    NAME: "Parallel_Amodal_Visible_Head"
    VERSION: 3
    ATTENTION_MODE: "attention"
    GT_AMODAL_WEIGHT: 1.0
    GT_VISIBLE_WEIGHT: 1.0
    AMODAL_FEATURE_MATCHING: (3,4)     # index, e.g:(0,1,2,3)
    AMODAL_FM_BETA: (0.01,0.05)
    RECLS_NET:
      NAME: "ReclsConvFCHead"
      MODE: "adaptive"
      GT_WEIGHT: 0.1
      RESCORING: False
    RECON_NET:
      NAME: "General_Recon_Net"
      NORM: ""
      BOX_THS: 0.8
      MASK_THS: 0.95
      NUM_CONV: 2
      ALPHA: 3.0
      RESCORING: True
      LOAD_CODEBOOK: True
      MEMORY_REFINE: True
      MEMORY_REFINE_K: 16
TEST:
  EVAL_AMODAL_TYPE: "AMODAL_VISIBLE"
OUTPUT:
  TRAIN_VERSION: 'DAIS'
OUTPUT_DIR: 'output/RGB_NORMAL_RAN'
SOLVER:
  WARMUP_ITERS: 10000
  WARMUP_METHOD: "smooth"
  WARMUP_FACTOR: 0.001